
var _ = require('../../');
var eq = _.test.eq;
var ok = _.test.ok;

function wait(ms, cb){ setTimeout(cb, ms); }

test("threshold", function(callback){

    var called = 0;
    var mw = _.middleware.threshold(20, function(req, res, duration){
        ok(duration > 20);
        called++;
    });

    res = { end: function(){} };
    mw({}, res, function(){ })

    res.end();

    res = { end: function(){} };
    mw({}, res, function(){ });

    await{ wait(30, defer()); }

    res.end();

    eq(called, 1);

    callback();
});


