
var _ = require('../');
var eq = _.test.eq;
var ok = _.test.ok;

var root = _.path.fun(_.path.normalize(__dirname + "/build-data/"));

exports.testFetchModule = testFetchModule;
// exports.testFetchModules = testFetchModules;

function testFetchModule(done){

    var calls = 0;
    var expectedCalls = 1;

    done(function(){ eq(calls, expectedCalls); });

    var err = null;
    var mod = null;

    // await{ _.build.fetchModule(root("bad", "bad-global.tjs"), defer(var err, mod)); }

    await{ _.build.fetchModule(root("not-there", "not-there.tjs"), defer(err, mod)); }
    eq(err, null);
    eq(mod, null);

    await{ _.build.fetchModule(root("bad", "bad-global.tjs"), defer(err, mod)); }
    ok(err);
    eq(mod, undefined);

    await{ _.build.fetchModule(root("bad", "bad-relative.tjs"), defer(err, mod)); }
    ok(err);
    eq(mod, undefined);

    await{ _.build.fetchModule(root("bad", "bad-abs.tjs"), defer(err, mod)); }
    ok(err);
    eq(mod, undefined);

    await{ _.build.fetchModule(root("bad"), defer(err, mod)); }
    eq(err, null);
    eq(mod, null);

    await{ _.build.fetchModule(root("badpath"), defer(err, mod)); }
    eq(err, null);
    eq(mod, null);
    
    await{ _.build.fetchModule("badpath", defer(err, mod)); }
    eq(err, null);
    eq(mod, null);

    await{ _.build.fetchModule(root("good", "one.tjs"), defer(err, mod)); }
    eq(err, null);
    eq(mod, {one:'one'});

    await{ _.build.fetchModule(root("good", "two.js"), defer(err, mod)); }
    eq(err, null);
    eq(mod, {two:'two'});

    calls++;
}

