#!/bin/bash

echo "(function(){"

cat ./deps/underscore.js

echo "(function(){"
cat ./deps/moment.min.js 
echo "_.moment = moment;" 
echo "delete this.moment;" 
echo "})();"

echo "(function(){"
cat ./deps/handlebars.min.js
echo "_.hb = Handlebars;" 
echo "delete this.Handlebars;" 
echo "})();"

echo "(function(){"
cat ./deps/deep-diff.min.js
echo "_.diff = DeepDiff;" 
echo "delete this.DeepDiff;" 
echo "})();"

echo "(function(){"
cat ./deps/underscore.string.min.js 
echo "})();"

echo "(" 
node -e "console.log(require('./lib/lodash.js').mixin.toString())" 
echo ")(_);" 

echo "(" 
node -e "console.log(require('./lib/common.js').mixin.toString())" 
echo ")(_);" 

echo "_.log = (" 
node -e "console.log(require('./lib/log.js').mixin.toString())" 
echo ")(_);" 

echo "_.format = (" 
node -e "console.log(require('./lib/format.js').library.toString())" 
echo ")(_);" 

echo "_.uuid = (" 
node -e "console.log(require('./lib/uuid.js').library.toString())" 
echo ")(_);" 

echo "_.sha256 = (" 
node -e "console.log(require('./lib/sha256.js').library.toString())" 
echo ")(_);" 

echo "_.string_builder = (" 
node -e "console.log(require('./lib/string_builder.js').library.toString())" 
echo ")(_);" 

echo "_.test = (" 
node -e "console.log(require('./lib/test.js').library.toString())" 
echo ")(_);" 

echo "_.url = (" 
node -e "console.log(require('./lib/url.js').library.toString())" 
echo ")(_);" 

echo "_.querystring = (" 
node -e "console.log(require('./lib/querystring.js').library.toString())" 
echo ")(_);" 

echo "_.http_base = (" 
node -e "console.log(require('./lib/http_base.js').library.toString())" 
echo ")(_);" 

echo "_.http = (" 
node -e "console.log(require('./lib/http.client.js').library.toString())" 
echo ")(_);" 

#echo "_.mixin(_.string.exports());" 

echo "(" 
node -e "console.log(require('./lib/client.js').mixin.toString())" 
echo ")(_);" 

echo "_.ns = (" 
node -e "console.log(require('./lib/ns.js').mixin.toString())" 
echo ")(_);" 

echo "_.hook = (" 
node -e "console.log(require('./lib/hook.js').mixin.toString())" 
echo ")(_);" 

echo "_.eventEmitter = (" 
node -e "console.log(require('./lib/eventEmitter.js').mixin.toString())" 
echo ")(_);" 
echo "_.event_emitter = _.eventEmitter;" 
echo "_.events = {};" 
echo "_.eventEmitter(_.events);" 

echo "_.timer = (" 
node -e "console.log(require('./lib/timer.js').library.toString())" 
echo ")(_);" 
 
echo "})();" 
