#!/bin/bash
shopt -s nullglob
bin/resolve_run tamejs/lib/main.js ./test/async.test.tjs > ./test/async.test.js &&
bin/resolve_run expresso/bin/expresso && 
bin/resolve_run dry-test/bin/dry-test ./lib/*.test.js ./lib/*.test.tjs ./lib/*/*.test.js ./lib/*/*.test.tjs && node ./test_client/run.js


